definitions:
  models.Task:
    properties:
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    get:
      description: Trả về danh sách task hiện có
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      summary: Lấy danh sách tất cả công việc
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Tạo task mới với JSON
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Tạo công việc mới
      tags:
      - tasks
swagger: "2.0"
