basePath: /
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Task:
    properties:
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: REST API sử dụng Fiber và Swagger
  title: Fiber Todo API
  version: "1.0"
paths:
  /Tasks/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID của task
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      tags:
      - tasks
    get:
      consumes:
      - application/json
      description: Trả về một task duy nhất dựa trên ID
      parameters:
      - description: ID của task
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      tags:
      - tasks
  /tasks:
    get:
      description: Trả về danh sách task hiện có
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      summary: Lấy danh sách tất cả công việc
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Tạo task mới với JSON
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Tạo công việc mới
      tags:
      - tasks
  /tasks/{id}:
    put:
      consumes:
      - application/json
      description: Nhận JSON và cập nhật nội dung task
      parameters:
      - description: ID của task
        in: path
        name: id
        required: true
        type: integer
      - description: Task cần cập nhật
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Cập nhật công việc theo ID
      tags:
      - tasks
swagger: "2.0"
